[package]
name = "uio-buffer"
version = "0.1.0"
authors = ["Andreas Wass <andreas.wass@dalelven.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
